# This script visualizes a phylogenetic tree of Lactobacillus crispatus
# reconstructed using StrainPhlAn. Tip labels from the tree (initially
# sample IDs) are mapped to user-defined codes and annotated with metadata.
# The tree is midpoint-rooted and displayed in a circular layout, with tip
# colors representing the sample source (e.g. human vagina, mouth) and
# shapes distinguishing sample types based on ID patterns.
#
# The script requires a metadata file (phylogeny_metadata.tsv) containing:
#   - Code: label used for plotting
#   - SampleID: identifier matching StrainPhlAn tip labels
#   - Source: origin of each sample (used for coloring)

# Load libraries

library(ape)
library(ggtree)
library(tidyverse)
library(phytools)
library(phangorn)
library(ggnewscale)
library(svglite)

# Load files and directories
dir_project <- 
  "../../"

tree_file <- 
  file.path(
  dir_project,
  "results/strain_level_analyses/isala/phylogeny/strainphlan",
  "RAxML_bestTree.t__SGB7045.StrainPhlAn4.tre"
)

metadata_file <- 
  file.path(
  dir_project,
  "data/phylogeny_metadata.tsv"
)

output_file <- 
  file.path(
  dir_project,
  "results/strain_level_analyses/isala/phylogeny",
  "tree_circular.svg"
)

# Load metadata and standardize column names
metadata <- 
  read_tsv(metadata_file) %>%
  clean_names() %>%
  rename(
    sampleID = sampleid,
    code = code,
    source = source
  )

# Load phylogenetic tree generated by StrainPhlAn
tree <- 
  read.tree(tree_file)

# Match tree tip labels (sample IDs) to plotting codes
match_code <- 
  match(tree$tip.label, metadata$sampleID)

tree$tip.label <- 
  ifelse(
  !is.na(match_code),
  metadata$code[match_code],
  tree$tip.label
)

# Root the tree using midpoint rooting for better visualization
rooted_tree <- 
  midpoint.root(tree)

# Attach metadata to each tip for plotting
tip_data <- 
  tibble(code = rooted_tree$tip.label) %>%
  left_join(metadata, by = "code"
  )

# Define color palette for different sample sources
palette2 <- c(
  "#B15928",
  "#1F78B4",
  "#B2DF8A",
  "#33A02C",
  "#E31A1C",
  "#FDBF6F",
  "#FF7F00",
  "#CAB2D6",
  "#6A3D9A",
  "#A6CEE3"
)

# Generate circular phylogenetic tree plot
p <- 
  ggtree(rooted_tree, layout = "circular", size = 0.5) %<+%
  tip_data +
  geom_tiplab(size = 3, hjust = 0, offset = 0.008) +   
  geom_tippoint(
    aes(
      color = source_cleaned,
      shape = grepl("^F|AM", label)   # Separate Isala strains for visualization
    ),
    size = 2
  ) +
  scale_shape_manual(
    values = c(`TRUE` = 17, `FALSE` = 16)
  ) +
  scale_color_manual(values = palette2, na.translate = FALSE) +                
  geom_treescale(fontsize = 4) +
  theme_tree2() +
  theme(
    axis.text  = element_blank(),
    axis.ticks = element_blank(),
    axis.line  = element_blank(),
    panel.grid = element_blank()
  )

p

# Save final figure
ggsave(
  output_file,
  plot = p,
  units = "cm",
  width = 40,
  height = 40,
  dpi = 300
)